spring.application.name=mentorai-backend

spring.datasource.url=jdbc:mysql://localhost:3306/mentorai
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

jwt.secret=mentorai_super_secret_key_very_long_secure_12345678901234567890
jwt.expiration=86400000

youtube.api.key=Google_api_key